# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_dir.global_validation_pb2 as global__validation__pb2


class GlobalValidationStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GlobalValidate = channel.unary_unary(
                '/GlobalValidation/GlobalValidate',
                request_serializer=global__validation__pb2.Transaction.SerializeToString,
                response_deserializer=global__validation__pb2.Result.FromString,
                )


class GlobalValidationServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GlobalValidate(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlobalValidationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GlobalValidate': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalValidate,
                    request_deserializer=global__validation__pb2.Transaction.FromString,
                    response_serializer=global__validation__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GlobalValidation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GlobalValidation(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GlobalValidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GlobalValidation/GlobalValidate',
            global__validation__pb2.Transaction.SerializeToString,
            global__validation__pb2.Result.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
