# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_db.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='update_db.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fupdate_db.proto\"6\n\x11UpdateTransaction\x12\x13\n\x0btransaction\x18\x01 \x01(\x0c\x12\x0c\n\x04rank\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty24\n\x08UpdateDB\x12(\n\x08UpdateDB\x12\x12.UpdateTransaction\x1a\x06.Empty\"\x00\x62\x06proto3'
)




_UPDATETRANSACTION = _descriptor.Descriptor(
  name='UpdateTransaction',
  full_name='UpdateTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='UpdateTransaction.transaction', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank', full_name='UpdateTransaction.rank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=73,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['UpdateTransaction'] = _UPDATETRANSACTION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateTransaction = _reflection.GeneratedProtocolMessageType('UpdateTransaction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETRANSACTION,
  '__module__' : 'update_db_pb2'
  # @@protoc_insertion_point(class_scope:UpdateTransaction)
  })
_sym_db.RegisterMessage(UpdateTransaction)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'update_db_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_UPDATEDB = _descriptor.ServiceDescriptor(
  name='UpdateDB',
  full_name='UpdateDB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=84,
  serialized_end=136,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateDB',
    full_name='UpdateDB.UpdateDB',
    index=0,
    containing_service=None,
    input_type=_UPDATETRANSACTION,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATEDB)

DESCRIPTOR.services_by_name['UpdateDB'] = _UPDATEDB

# @@protoc_insertion_point(module_scope)
