# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_dir.update_db_pb2 as update__db__pb2


class UpdateDBStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateDB = channel.unary_unary(
                '/UpdateDB/UpdateDB',
                request_serializer=update__db__pb2.UpdateTransaction.SerializeToString,
                response_deserializer=update__db__pb2.Empty.FromString,
                )


class UpdateDBServicer(object):
    """Missing associated documentation comment in .proto file"""

    def UpdateDB(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateDB': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDB,
                    request_deserializer=update__db__pb2.UpdateTransaction.FromString,
                    response_serializer=update__db__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UpdateDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UpdateDB(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def UpdateDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UpdateDB/UpdateDB',
            update__db__pb2.UpdateTransaction.SerializeToString,
            update__db__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
